AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'
Description: DWIF process service now kb articlesdevsecops stack resources.

Parameters:
  Environment:
    Type: String
    Description: S3Bucket Path where the templates are stored
    
  AmazonLinux2ImageID:
   Description: "Amazon Linux 2 Latest AMI ID"
   Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'

  TenantAcronym:
    Type: String
    Description: tenant acronym
    Default: devsecops
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9-_]*"
  
  DeploymentVer:
    Type: String
    Description: deployment version
    Default: v1
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9-_]*"

  AssetBucketParam:
    Type: String
    Description: Bucket used to upload assets
    #Default: sn-kb-articles-to-azure
    Default: sn-kb-articles
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9-_]*"
  
  ENVblobconnectionstring:
    Type: String
    Description: blob connection string
    Default: "abc"
    #AllowedPattern: "[a-zA-Z][a-zA-Z0-9-._]*"
    
  ENVcontainername:
    Type: String
    Description: storage container name
    Default: ai-knowledge-test
    #AllowedPattern: "[a-zA-Z][a-zA-Z0-9-_]*"
  
  ENVSNSNOTIFTOPIC:
    Type: String
    Description: SNS notification topic.
    Default: arn:aws:sns:us-west-2:516595067404:dwiflabMonitorLambda
    AllowedPattern: "[a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*"
  
  ENVITSMACCOUNT:
    Type: String
    Description: itsm account name
    Default: aws.saic

  ENVITSMACCOUNTPWD:
    Type: String
    Description: itsm_account_pass
    Default: M1P1amazonintONE1!

  ENVITSMINSTANCE:
    Type: String
    Description: itsm instance
    Default: scienceapplicationsintlcorpsaicdemo9.service-now.com
  
  ENVKBSOURCE:
    Type: String
    Description: KB source
    Default: /es3?id=kb_article_view&sysparm_article=

  ENVKBINSTANCE:
    Type: String
    Description: itsm instance
    Default: es3dev.saic.com

  ENVCHATCOMPLDEPNAME:
    Type: String
    Description: chat deployment name
    Default: DWIF-GPT4o

  ENVAZUREOPENAIENDPT:
    Type: String
    Description: openai endpoint
    Default: https://dwifopenaieast2.openai.azure.com/

  ENVAZUREOPENAIKEY:
    Type: String
    Description: open ai api key
    Default: eb8b3dedcabf4705b7302196c8091c4e

  ENVAZUREAISEARCHAPIKEY:
    Type: String
    Description: search api key
    Default: abc

  ENVSEARCHENDPOINT:
    Type: String
    Description: search endpoint
    Default: https://cognitiveservice-east.search.windows.net
    
  ENVSEARCHINDEX:
    Type: String
    Description: search index
    Default: ito-pilot-index-v

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "General Configuration"
        Parameters:
          - TenantAcronym
          - AssetBucketParam

    ParameterLabels:
      TenantAcronym:
        default: "Tenant Acronym"
      AssetBucketParam:
        default: "DWIF Assets Bucket"
      LanguageCode:
        default: "Default language code"

Resources:
  ################################################################################
  #
  # ProdductsAndServices state machine resources (execution role, lambda, and state machine)
  #
  ################################################################################
  LambdaPipelineFunctionRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: "This wildcard is present as state machine lambda needs to be able to access contents within the bucket!"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Path: /
      Policies:
        - PolicyName: !Sub "${TenantAcronym}-productsservices"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              ## S3
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:PutObjectTagging"
                  - "s3:PutObjectVersionTagging"
                Resource:
                  - !Sub "arn:aws:s3:::${AssetBucketParam}/*"

              ## CloudWatch Logs
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
  ################################################################################
  
  # Lambda Functions.
  AdvBotChatLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "dwif-devsecops-lambda1-${DeploymentVer}"
      CodeUri: ./app
      Timeout: 900
      MemorySize: 512
      Handler: aws-devsecops-lambda1.lambda_handler
      Layers:
        - 'arn:aws:lambda:us-west-2:516595067404:layer:ijson-layer:1'
        - 'arn:aws:lambda:us-west-2:516595067404:layer:pypandoc:2'
      Role: !GetAtt LambdaPipelineFunctionRole.Arn
      Runtime: python3.12
      Environment:
        Variables:
          SNSTopicARN: !Ref ENVSNSNOTIFTOPIC
          ITSM_ACCOUNT: !Ref ENVITSMACCOUNT
          ITSM_ACCOUNT_PWD: !Ref ENVITSMACCOUNTPWD
          ITSM_INSTANCE: !Ref ENVITSMINSTANCE


  AdvBotLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "dwif-devsecops-lambda2-${DeploymentVer}"
      CodeUri: ./app
      Timeout: 250   
      MemorySize: 512
      Handler: aws-devsecops-lambda2.lambda_handler
      Layers:
        - 'arn:aws:lambda:us-west-2:516595067404:layer:openai_v1370:1'
        - 'arn:aws:lambda:us-west-2:516595067404:layer:azure-storage-blob:9'
      Role: !GetAtt LambdaPipelineFunctionRole.Arn
      Runtime: python3.12
      Environment:
        Variables:
          ITSM_ACCOUNT: !Ref ENVITSMACCOUNT
          ITSM_ACCOUNT_PWD: !Ref ENVITSMACCOUNTPWD
          ITSM_INSTANCE: !Ref ENVITSMINSTANCE
  
  
Outputs:
  ServiceRoleArn:
    Value: !GetAtt LambdaPipelineFunctionRole.Arn
    Description: Role Arn (Lambda Function ARN)

  LambdaFunctionList:
    Value: !Join [
      ",", [
        !Ref AdvBotChatLambdaFunction,
        !Ref AdvBotLambdaFunction   
      ],
    ]
    Description: List of Lambda functions